name : Request Form
description: This is the description for a request
title: Requested 

body: 
  - type: markdown
    attributes:
      value: |
        Thanks for requesting!
  - type: input
    id: request
    attributes:
      label: Request
      description: Please insert your request.
      placeholder: ex. Can you create a new report that tells us the latest end date for all asssessments
    validations:
      required: true
