name : XYZ Form
description: This is a description the XYZ form.
labels: ["bug, enhancement"]

body: 
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Your Name
      description: We need your name to know who you are!
      placeholder: ex. James
    validations:
      required: true
