name : Person Details Form
description: This is a description for the person.
title: Person Details
labels: ["bug, enhancement"]

body: 
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Your Name
      description: We need your name to know who you are!
      placeholder: ex. James
    validations:
      required: tru
    - type: dropdown
      id: person
      attributes: 
      label: Person
      description: Who are you choosing?
      options: ["James, Andy, Steve"]
      validations:
      required: true
