name : Request Form
description: Please submit your request below
title: Request

body:
- type: dropdown
  id: download
  attributes:
    label: How did you download the software?
    options:
      - Homebrew
      - MacPorts
      - apt-get
      - Built from source
  validations:
    required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Use this box to add a more details 
      placeholder:
    validations:
      required: false
