name : Request Form
description: This is the description for a request
title: Request for

body: 
  - type: markdown
    attributes:
      value: |
        Thanks for requesting!
  - type: input
    id: request
    attributes:
      label: Request
      description: Please insert your request.
      placeholder: ex. Can you create a new report for assessments?
    validations:
      required: true
  - type: markdown
    attributes:
    value: 
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Use this box to add a more details 
      placeholder:
    validations:
      required: false
