name : Request Form
description: Please submit your request below
title: Request

body:
  - type: input
    id: Request
    attributes:
      label: Request
      description: Please submit your request.
      placeholder: ex. Can I have a report for assessments?
    validations:
      required: true
  - type: textarea
    id: more-details
    attributes:
      label: Description
      description: Use this box to add more details!
    validations:
      required: false
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: What project does this request belong to?
      options:
        - 1
        - 2
        - 3
    validations:
      required: true
  - type: dropdown
    id: strategy
    attributes:
      label: Strategy
      multiple: false
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: input
    id: start-date
    attributes:
      label: Start date
  - type: input
    id: end-date
    attributes:
      label: End date
